"""empty message

Revision ID: 4f2bc7b2e20e
Revises: 
Create Date: 2023-03-21 10:37:27.136958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2bc7b2e20e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_priority',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_product',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_status',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=10), nullable=False),
    sa.Column('pure_letter_name', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('pure_letter_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('manager_to_team',
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], )
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=False),
    sa.Column('status_update_date', sa.Date(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('plan', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['project_priority.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['project_product.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['project_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_ALL', sa.Boolean(), nullable=False),
    sa.Column('access_RD', sa.Boolean(), nullable=False),
    sa.Column('access_PMO', sa.Boolean(), nullable=False),
    sa.Column('access_SW', sa.Boolean(), nullable=False),
    sa.Column('access_VV', sa.Boolean(), nullable=False),
    sa.Column('access_SYS', sa.Boolean(), nullable=False),
    sa.Column('access_HW', sa.Boolean(), nullable=False),
    sa.Column('manage_ALL', sa.Boolean(), nullable=False),
    sa.Column('manage_RD', sa.Boolean(), nullable=False),
    sa.Column('manage_PMO', sa.Boolean(), nullable=False),
    sa.Column('manage_SW', sa.Boolean(), nullable=False),
    sa.Column('manage_VV', sa.Boolean(), nullable=False),
    sa.Column('manage_SYS', sa.Boolean(), nullable=False),
    sa.Column('manage_HW', sa.Boolean(), nullable=False),
    sa.Column('config_ALL', sa.Boolean(), nullable=False),
    sa.Column('config_RD', sa.Boolean(), nullable=False),
    sa.Column('config_PMO', sa.Boolean(), nullable=False),
    sa.Column('config_SW', sa.Boolean(), nullable=False),
    sa.Column('config_VV', sa.Boolean(), nullable=False),
    sa.Column('config_SYS', sa.Boolean(), nullable=False),
    sa.Column('config_HW', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_operation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('log_time', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_to_project',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('year_of_project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'year')
    )
    op.create_table('resource',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('Jan', sa.Integer(), nullable=True),
    sa.Column('Feb', sa.Integer(), nullable=True),
    sa.Column('Mar', sa.Integer(), nullable=True),
    sa.Column('Apr', sa.Integer(), nullable=True),
    sa.Column('May', sa.Integer(), nullable=True),
    sa.Column('Jun', sa.Integer(), nullable=True),
    sa.Column('Jul', sa.Integer(), nullable=True),
    sa.Column('Aug', sa.Integer(), nullable=True),
    sa.Column('Sep', sa.Integer(), nullable=True),
    sa.Column('Oct', sa.Integer(), nullable=True),
    sa.Column('Nov', sa.Integer(), nullable=True),
    sa.Column('Dec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id', 'year'], ['year_of_project.project_id', 'year_of_project.year'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource')
    op.drop_table('year_of_project')
    op.drop_table('user_to_project')
    op.drop_table('project_operation_log')
    op.drop_table('user_permission')
    op.drop_table('project')
    op.drop_table('manager_to_team')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('role')
    op.drop_table('project_status')
    op.drop_table('project_product')
    op.drop_table('project_priority')
    # ### end Alembic commands ###
